repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/lietu/go-pre-commit
    rev: v0.1.0
    hooks:
    - id: gofumpt
    - id: go-mod-tidy
