name: Code Check

on:
    push:
      branches:
        - develop
    pull_request:
      branches:
        - master
        - develop
        - test-release

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install pre-commit hooks
        run: pre-commit install

      - name: Run pre-commit
        run: pre-commit run --all-files

  tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Install go-acc
        run: go install github.com/ory/go-acc@latest

      - name: Run tests
        run: |
          export MONGO_URI="mongodb://localhost:27017"
          go-acc --tags=test -o coverage.out ./...

      - name: Verify coverage
        run: |
          COVERAGE=$(go tool cover -func=./coverage.out | grep total: | awk '{print $3}')
          THRESHOLD=70.0
          RESULT=$(awk -v cov="$COVERAGE" -v thr="$THRESHOLD" 'BEGIN {if (cov < thr) print 1; else print 0}')

          if [ "$RESULT" -eq 0 ]; then
            echo "Coverage ($COVERAGE%) meets the threshold ($THRESHOLD%)"
          else
            echo "Coverage ($COVERAGE%) is below the threshold ($THRESHOLD%)"
            exit 1
          fi
